name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main, feature/** ]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    env:
      ROS_DISTRO: humble
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src/logistics_robot
      
      - name: Setup ROS
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ env.ROS_DISTRO }}
      
      - name: Install dependencies
        run: |
          git clone -b humble https://github.com/IFRA-Cranfield/IFRA_LinkAttacher.git src/IFRA_LinkAttacher
          cd src/IFRA_LinkAttacher
          git checkout b056289ba93ccb549db98926dcbb9679642d0c8d
          cd ../..
          sudo apt-get update
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Build
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          colcon build --event-handlers console_direct+

      - name: Test
        run: |
          source /opt/ros/${ROS_DISTRO}/setup.bash
          source install/setup.bash
          colcon test --base-paths src/logistics_robot --event-handlers console_direct+
          colcon test-result --verbose